import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { existsSync, mkdirSync, copyFileSync, readFileSync } from "fs";
import { join } from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
For source visit github.com/RegardsKiki2/bevia-your-ai-co-pilot
Path: packages/obsidian-plugin/src
*/`;

const prod = process.argv[2] === "production";

const PLUGIN_ID = "bevia-navigator";

// Auto-install into your Obsidian vault so a reload picks up the build — no
// hand-copying main.js/manifest.json every time. Point at your vault root via
// EITHER:
//   • env var:   BEVIA_VAULT_DIR="/path/to/My Vault" npm run build
//   • or a file: packages/obsidian-plugin/.vault-dir  (one line: the vault root)
// The file is gitignored, so you set it once and forget it. If neither is set,
// the build still produces main.js in this folder (you'd copy it yourself).
function resolveVaultDir() {
  if (process.env.BEVIA_VAULT_DIR && process.env.BEVIA_VAULT_DIR.trim()) {
    return process.env.BEVIA_VAULT_DIR.trim();
  }
  try {
    const p = readFileSync(new URL("./.vault-dir", import.meta.url), "utf8").trim();
    if (p) return p;
  } catch { /* no file — fine */ }
  return null;
}

const vaultDir = resolveVaultDir();
const installDir = vaultDir ? join(vaultDir, ".obsidian", "plugins", PLUGIN_ID) : null;

function installToVault() {
  if (!installDir) {
    console.log(
      "[bevia] built main.js here. Set BEVIA_VAULT_DIR or create a .vault-dir " +
        "file to auto-install into your vault.",
    );
    return;
  }
  try {
    mkdirSync(installDir, { recursive: true });
    for (const f of ["main.js", "manifest.json", "styles.css"]) {
      if (existsSync(f)) copyFileSync(f, join(installDir, f));
    }
    console.log(`[bevia] installed plugin → ${installDir} (reload Obsidian to pick it up)`);
  } catch (e) {
    console.warn(`[bevia] could not install to vault: ${e.message}`);
  }
}

// esbuild plugin: run the install on every successful build — once for prod,
// and on each rebuild in watch/dev mode.
const installPlugin = {
  name: "install-to-vault",
  setup(build) {
    build.onEnd((result) => {
      if (!result.errors || result.errors.length === 0) installToVault();
    });
  },
};

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  plugins: [installPlugin],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
